#! /bin/bash
#
# File: set-project-jenkins
#
# Purpose: Sets the default project to 
#          the Jenkins project.

echo 'Setting the defaul to the Jenkins project'
gcloud config set project jenkins-cpo200
gcloud config list


